name: Build FlClash for Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          lfs: true

      - name: Pull LFS files
        run: git lfs pull

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: List files for diagnostics
        continue-on-error: true
        run: |
          echo "Listing files in the root directory:"
          dir
          echo "---"
          echo "Listing files in libclash directory:"
          dir libclash
          echo "---"
          echo "Listing files in libclash/windows directory:"
          dir libclash\windows
          echo "---"
          echo "Checking specifically for FlClashCore.exe:"
          dir libclash\windows\FlClashCore.exe
        shell: cmd

      - name: Build Windows executable
        run: flutter build windows --release

      - name: Archive Release
        uses: actions/upload-artifact@v4
        with:
          name: FlClash-Windows-Release
          path: build/windows/runner/Release 